In [4]:
import numpy as np

In [7]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])
A

array([[2, 1, 1, 0],
       [4, 3, 3, 1],
       [8, 7, 9, 5],
       [6, 7, 9, 8]])

In [21]:
L = np.identity(4, dtype=np.int)
U = A

In [20]:
for k in range(1, 4):
h

array([[2, 1, 1, 0],
       [4, 3, 3, 1],
       [8, 7, 9, 5],
       [6, 7, 9, 8]])

In [5]:
A = np.array([[2,0,0], [0,2,0], [0,0,2]])
A

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [6]:
B = np.array([[2,3,4,5], [6,7,8,9], [1,2,3,4]])
B

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [1, 2, 3, 4]])

In [7]:
np.matmul(A, B)

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18],
       [ 2,  4,  6,  8]])